 # Análise e formatação de dados de vendas do PostgreSQL

 ## Objetivo

 Análise exploratória de dados de vendas: formatação e visualização estratégica para geração de insights e suporte à tomada de decisão.

 - Quais são os melhores 5 produtos de cada categoria com base no total de venda?
 - Como realizar a imputação de valores ausentes na coluna quantity através da modelagem do preço unitário por produto, região e descontos?

## Dicionário de dados:

![Print 1](imagens/SuperStore_ERD.png)

## Desenvolvimento

A tabela abaixo detalha a representatividade dos 5 principais produtos de cada categoria. Observa-se que o segmento de Tecnologia lidera o volume de vendas, enquanto o de Material de Escritório apresenta o menor desempenho no período analisado.

In [ ]:
SELECT *
FROM(
     SELECT pro.category,
	        pro.product_name,
	        ROUND(CAST(SUM(ord.sales) AS NUMERIC), 2) AS product_total_sales,
	        ROUND(CAST(SUM(ord.profit) AS NUMERIC), 2) AS product_total_profit,
	        RANK() OVER(PARTITION BY pro.category
	             ORDER BY SUM(ord.sales) DESC)
	             AS product_rank
     FROM orders AS ord
     INNER JOIN products AS pro
     ON pro.product_id = ord.product_id
	 GROUP BY pro.category, pro.product_name
     ORDER BY pro.product_name) AS ranked_results
WHERE product_rank <= 5
ORDER BY category ASC, product_total_sales DESC;

           category  ... product_rank
0         Furniture  ...            1
1         Furniture  ...            2
2         Furniture  ...            3
3         Furniture  ...            4
4         Furniture  ...            5
5   Office Supplies  ...            1
6   Office Supplies  ...            2
7   Office Supplies  ...            3
8   Office Supplies  ...            4
9   Office Supplies  ...            5
10       Technology  ...            1
11       Technology  ...            2
12       Technology  ...            3
13       Technology  ...            4
14       Technology  ...            5

[15 rows x 5 columns]

O tratamento dos dados nulos foca na estimativa de volumetria, utilizando fatores de precificação relevantes (descontos, mercado e região) para inferir as quantidades faltantes com maior precisão.

In [ ]:
WITH missing AS (
	SELECT product_id,
		   discount, 
		   market,
		   region,
		   sales,
		   quantity
	FROM orders 
	WHERE quantity IS NULL
), 

unit_prices AS (SELECT o.product_id,
	                   CAST(o.sales / o.quantity AS NUMERIC) AS unit_price
FROM orders o
RIGHT JOIN missing AS m 
	ON o.product_id = m.product_id
	AND o.discount = m.discount
WHERE o.quantity IS NOT NULL
)

SELECT DISTINCT m.*,
	ROUND(CAST(m.sales AS NUMERIC) / up.unit_price,0) AS calculated_quantity
FROM missing AS m
INNER JOIN unit_prices AS up
	ON m.product_id = up.product_id;

         product_id  discount  market  ...    sales  quantity  calculated_quantity
0  FUR-ADV-10000571      0.00    EMEA  ...  438.960       NaN                    4
1  FUR-ADV-10004395      0.00    EMEA  ...   84.120       NaN                    2
2   FUR-BO-10001337      0.15      US  ...  308.499       NaN                    3
3  TEC-STA-10003330      0.00  Africa  ...  506.640       NaN                    2
4  TEC-STA-10004542      0.00  Africa  ...  160.320       NaN                    4

[5 rows x 7 columns]

## Conclusão

Portanto, a estruturação e o tratamento da consulta foram essenciais para garantir a integridade da base de dados, viabilizando análises mais consistentes e a geração de padrões, tendências ou comportamento relevantes sobre o comportamento de vendas.